import type { Metadata } from "next";
import { Be_Vietnam_Pro } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Hero from "@/assets/hero-image-wr.jpg";
import Logo from "@/assets/Logo.svg";

const sansFont = Be_Vietnam_Pro({
  variable: "--font-sans",
  weight: ["500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sansFont.variable} relative antialiased dark bg-background text-foreground font-sans`}
      >
        <div className="grid">
          <Image
            src={Hero}
            alt=""
            className="w-full h-[25vh] object-cover col-start-1 row-start-1"
          />
          <Image
            src={Logo}
            alt="World Ranks Logo"
            className="col-start-1 row-start-1 self-center justify-self-center"
          />
        </div>
        {children}
      </body>
    </html>
  );
}
